### register

POST http://127.0.0.1:3000/api/v1/register
Content-Type: application/json

{
    "liveName": "ライブの名称",
    "date": "10/27",
    "time": "19:00~",
    "place": "here",
    "description": "これが説明",
    "deadline": "10/28"
}

### liveInfo

GET  http://127.0.0.1:3000/api/v1/liveInfo/359270e492


### user
GET http://127.0.0.2:3000/api/v1/user